### ISSUE TITLE
Region or domain ambiguity

### ISSUE THREAD

**Issue by rainqubit** [jgoralcz/aki-api#15]
https://github.com/jgoralcz/aki-api/blob/1be423a0b96c0618cb11484c7eb2e418226bc54b/functions/start.js#L15

you should make it clear that you need to add `.akinator.com` to the region or add it in the code.
loved your api tho ❤️

**Comment by jgoralcz** [comment]
This issue is actually from akinator changing their uri's again. The reason why adding ".akinator.com" works is because it defaults to the 'en2' server which is a newer server they have. I tested it out and even added "fasdlkfjaslfj" to the end of it, ultimately confirming that. I will begin updating them. Thank you for bringing this to my attention.
