### ISSUE TITLE
Issue with win function

### ISSUE THREAD

**Issue by sreejilv** [jgoralcz/aki-api#21]
When I calling the win function, getting the response like this !!!

{"completion":"KO - ELEM LIST IS EMPTY","parameters":{"elements":null,"NbObjetsPertinents":null}}

**Comment by jgoralcz** [comment]
Hm... I'm not seeing the same on my side. 
Could you try to answer the following to the best of your ability:
1) Which language did you try to use? 
2) At what step did you call the "win" function? (Step 5, 10, 20, when the probability was above .7)?
3) Was there any point where you could have made an error or a user did not respond for longer than 2 minutes?

**Comment by sreejilv** [comment]
1)  I am using language 'en'
2)  Calling the win function after 20th question and the probability above 80
3)  No

**Comment by jennasisis** [comment]
Heya, im getting the same error here.
@jgoralcz any idea on what's wrong?
If i had to guess, it'd be that it's not returning with any answers when the win function is called. There's no "answers" array.. in theory. Possibly because there's a minimum probability (determined by the api) for there to be answers?

**Comment by jgoralcz** [comment]
Do you have any input I can test on? Is there an error or is there no output? If it's an error, for the time being, you can try something like
```
const test = await aki.win(region, session, signature, step+1).catch( async (error) => {
            console.error(error);
            // your akinator next step logic
        });
```

**Comment by jennasisis** [comment]
Do you have a Discord? I'm using this lib with a bot I'm developing. That's where my input is coming from.
I haven't uploaded the code to my gitlab because of the bug, I'll send the link when I'm at my dev computer.

**Comment by jgoralcz** [comment]
Ahh. I don't use the callback functions myself, there may be a problem with that. I would highly recommend using async/await instead since you're already using async in a few places. At any rate, I do have a discord https://discord.gg/jBRcjf
so we can get to the bottom of it. I believe it must be the callback functions of the API that I've wanted to get rid of.

**Comment by jennasisis** [comment]
Ah I see, I'll switch the callback to the async version and run it from there.
Meanwhile, the link expired. What's your user?

**Comment by jennasisis** [comment]
Hey, realized this was resolved so

@sreejilv use the async version. That works. The callbacks don't.. for whatever reason

**Comment by jgoralcz** [comment]
callbacks were a legacy feature I was "supporting", but didn't want to look into it much because I don't like working with callbacks myself. I may look into either fixing it or removing it.
